name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
env:
  terraform-tflint-version: 'latest'
  
permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
        #

      - name: Format Terraform files
        run: terraform fmt -recursive

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master

      - name: Commit changes
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            if git diff --quiet; then
              echo "No changes to commit"
            else
              git commit -a -m "Fix end of file whitespace"
            fi
          else
            echo "Commit step skipped. Running on push event."
          fi

  lint-test-deploy:
    name: Lint, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
