name: Include Log Workflows

on: [pull_request]
#  push:
#    branches:
#      - main

jobs:
  include-workflows:
    name: Include Source Repository Workflows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/LerningGit/github_actions#<main>
#           LerningGit/github_actions
#           ref: main

      - name: Include Workflow 1
        uses: ./.github/workflows/action_gcp.yml

#       - name: Include Workflow 2
#         uses: ./.github/workflows/auto-commits.yml
